# Generated by Django 4.1.5 on 2023-01-27 17:55

from django.db import migrations, models
import simple_tenants.utils


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="file",
            field=models.ImageField(
                blank=True, upload_to=simple_tenants.utils.get_upload_path
            ),
        ),
    ]
