# Generated by Django 4.1.5 on 2023-01-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_poll_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="subdomain",
            new_name="prefix",
        ),
    ]
